import { PrismaClient } from "@prisma/client";
// PrismaClient: the main database client generated by Prisma.

import { Pool } from "pg";
// pg (node-postgres): the official PostgreSQL driver.
// Prisma 7 requires an external DB driver when using Direct Connection mode.

import { PrismaPg } from "@prisma/adapter-pg";
// PrismaPg: Prisma’s adapter that connects PrismaClient to the pg driver.
// This is REQUIRED in Prisma 7 because datasource URLs are no longer stored
// inside schema.prisma and "engineType: client" needs an adapter.

/**
 * Prisma Client Singleton Setup (Prisma 7 Compatible)
 *
 * Why this exists:
 * ----------------
 * Next.js (and Bun) performs hot reloads during development.
 * On every reload, the server code is re-executed.
 *
 * If we create a **new PrismaClient()** instance every time, it creates a new
 * PostgreSQL connection. After enough reloads, this leads to:
 *
 *   "Error: remaining connection slots are reserved"
 *
 * To avoid this, we store the PrismaClient instance on `globalThis`.
 * This allows us to reuse the same instance between reloads.
 *
 * In production:
 * - Only one instance is created anyway
 * - So we do not store it globally
 */
const globalForPrisma = globalThis as unknown as {
  prisma: PrismaClient | undefined;
};

/**
 * PostgreSQL Connection Pool Setup
 *
 * Why we need a pool:
 * -------------------
 * Prisma 7 removed datasource URLs from schema.prisma.
 * Instead, real DB drivers (like pg) handle connections.
 *
 * Here we create a PG connection pool using the DATABASE_URL
 * from prisma.config.ts (Prisma Migrate uses it) and .env.
 */
const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

/**
 * Prisma Adapter Setup (Prisma 7 Requirement)
 *
 * Prisma no longer connects directly to the database using the old engine.
 * Instead:
 * - pg handles the DB connection
 * - PrismaPg adapts PrismaClient to work with pg
 */
const adapter = new PrismaPg(pool);

/**
 * Create the Prisma Client
 *
 * If a client already exists on the global object, reuse it.
 * Otherwise, create a new PrismaClient using the PostgreSQL adapter.
 *
 * The adapter is mandatory in Prisma 7 unless you're using Accelerate.
 */
export const prisma =
  globalForPrisma.prisma ??
  new PrismaClient({
    adapter, // Required in Prisma 7 for direct DB connections
    // log: ["query", "error", "warn"], // Display useful logs during development
  });

/**
 * Store Prisma Client globally in development
 *
 * This prevents creating multiple new database connections
 * every time the app reloads during Next.js development.
 */
if (process.env.NODE_ENV !== "production") globalForPrisma.prisma = prisma;
